### ISSUE TITLE
can you share link to some decription for this kaHFM algorithms 

### ISSUE THREAD

**Issue by Sandy4321** [jirifilip/pykaHFM#1]
can you share link to some decription for this kaHFM algorithms 
some paper or any  pls

**Comment by Sandy4321** [comment]
is it source
https://www.researchgate.net/publication/336596908_How_to_Make_Latent_Factors_Interpretable_by_Feeding_Factorization_Machines_with_Knowledge_Graphs

https://github.com/sisinflab/HybridFactorizationMachines

**Comment by jirifilip** [comment]
Here it is https://arxiv.org/pdf/1909.05038.pdf
